# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ main ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prod-check:
    if: github.head_ref == 'refs/heads/testbranch'
    runs-on: ubuntu-latest
    steps:
      - run: echo "PR from on branch $GITHUB_REF"

